// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9cHShNIHr_Mv9nhvFdR_fBCh-ZPWO_w',
    appId: '1:177675589375:web:98f759a200f32771dedeca',
    messagingSenderId: '177675589375',
    projectId: 'group-b90ac',
    authDomain: 'group-b90ac.firebaseapp.com',
    storageBucket: 'group-b90ac.firebasestorage.app',
    measurementId: 'G-2X0X696DM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoFFKeK2_tyQjcTA6uKwU-MIHRnVGlxQ',
    appId: '1:177675589375:android:698d4972e67abc72dedeca',
    messagingSenderId: '177675589375',
    projectId: 'group-b90ac',
    storageBucket: 'group-b90ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClAfeDJS2iOTbBrdYol2TLQIe5DTwkKFQ',
    appId: '1:177675589375:ios:3fda4f867e9bef17dedeca',
    messagingSenderId: '177675589375',
    projectId: 'group-b90ac',
    storageBucket: 'group-b90ac.firebasestorage.app',
    iosBundleId: 'com.example.group414',
  );
}



